name:                hedgehog-checkers
version:             0.1.0.0
homepage:            https://github.com/bitemyapp/hedgehog-checkers#readme
license:             BSD3
author:              Chris Allen
maintainer:          cma@bitemyapp.com
copyright:           2017, Chris Allen
category:            Web
description:         hedgehog-checkers wraps up the expected properties associated with various standard type classes as Hedgehog properties.
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - base
    - containers
    - hedgehog
    - semigroupoids
  exposed-modules:
    - Hedgehog.Checkers

tests:
  tests:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - base
      - hedgehog
      - hedgehog-checkers
      - either
    ghc-options:
      - -threaded
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
