name:                hedgehog-checkers
version:             0.1.0.0
homepage:            https://github.com/bitemyapp/hedgehog-checkers#readme
license:             BSD3
author:              Chris Allen
maintainer:          cma@bitemyapp.com
copyright:           2017, Chris Allen
category:            Web
description:         hedgehog-checkers wraps up the expected properties associated with various standard type classes as Hedgehog properties.
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hedgehog >= 0.5 && < 0.6

library:
  source-dirs: src
  dependencies:
    - containers >= 0.4 && < 0.6
    - semigroups >= 0.9 && < 1
    - semigroupoids >= 5 && < 6
  exposed-modules:
    - Hedgehog.Checkers
    - Hedgehog.Checkers.Ugly.Function.Hack

tests:
  tests:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - hedgehog-checkers
      - either >= 4.3.2 && < 5
    ghc-options:
      - -threaded
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
